#!/bin/sh

RED="\e[1;31m"
GREEN="\e[1;32m"
RESET="\e[0m"

[ ! -d "$HOME"/.config/git ] && mkdir -p "$HOME"/.config/git && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Created git config directory." || \
    printf "%b\n" "${RED}ERROR:${RESET} Git directory exists, skipping."

ln -sf "$PWD/config" "$HOME/.config/git/config" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlinked git config file"
ln -sf "$PWD/ignore" "$HOME/.config/git/ignore" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlinked git ignore file"
