#!/bin/sh

GREEN="\033[1;32m"
RED="\033[1;31m"
RESET="\033[0m"

dep_chk(){
    for pr; do
    # The below command is being redirected to /dev/null, the output of the command with the standard input
    # and the errors is being redirected to /dev/null
        command -v "$@" 2>&1> /dev/null || printf '%b\n' "The program ${RED}${pr}${RESET} is not installed, install: ${pr}"
    done
}

dep_chk "tmux" "sxiv" "git" "dunst" "lynx" "sxhkd" "vim" "wget"

[ ! -L "$HOME"/.bashrc ] && \
    ln -sf "$PWD/.bashrc" "$HOME/.bashrc" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink successful! (bashrc)"
[ ! -L "$HOME"/.inputrc ] && \
    ln -sf "$PWD/.inputrc" "$HOME/.inputrc" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink successful! (inputrc)"
[ ! -L "$HOME"/.profile ] && \
    ln -sf "$PWD/.profile" "$HOME/.profile" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink successful! (profile)"
[ ! -L "$HOME"/.bash_profile ] && \
    ln -sf "$PWD/.profile" "$HOME/.bash_profile" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink successful! (bash_profile)"

# for user custom directory path
[ ! -d "$HOME"/.config ] && mkdir -p "$HOME"/.config
[ ! -L "$HOME"/.config/user-dirs.dirs ] && \
    ln -sf "$PWD/user-dirs.dirs" "$HOME/.config/user-dirs.dirs" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink successful. (user-dirs.dirs)"

DIR="vim tmux x11 dunst lynx gh git sxiv fontconfig wget sxhkd"

# check for the .config directory and make directories inside it
config="$HOME/.config"
if [ -d "${config}" ];
then
        for i in "${DIR}";
        do
            mkdir -p "${config}/${i}"
        done
else
        printf "%b\n" "The directory ${config} does not exist.\n${GREEN}MKDIR: ${RESET}Creating directories." && mkdir -p "$HOME"/.config
        if [ -d "${config}" ]; then
            for i in "${DIR}";
            do
                mkdir -p "${config}/${i}" && continue || break
            done
        fi
fi

for i in "$DIR";
do
    cd "$i" && ./setup
    cd - || printf "%b\n" "${RED}ERROR:${RESET} Directory $i does not exist" || \
        exit 1
done
