#!/bin/sh

set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"

program="vim tmux x11 dunst"
for i in $program; do
    cd $i && ./setup
    cd -
done
