#!/bin/sh

GREEN="\033[1;32m"
RESET="\033[0m"

[ ! -d "$HOME"/.config/gh ] && mkdir -p "$HOME"/.config/gh
[ ! -L "$HOME"/.config/gh/config.yml ] && \
    ln -sf "$PWD/config.yml" "$HOME/.config/gh/config.yml" && \
    printf "%b\n" "${GREEN}SUCCESS:${RESET} Symlink success. (github-cli)"
printf "\n%s\n" 'Might as well do gh auth --with-token <token>'
