#!/bin/sh

# This file runs when a DM logs you into a graphical session.

setbg &         # set the background with setbg script
#remaps &

autostart="dunst unclutter xcompmgr slstatus"

for program in $autostart; do
    pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1
