#!/bin/sh
type -p sxiv 2>/dev/null || echo '[!] The program sxiv is not installed.'
mkdir -p $HOME/.config/sxiv/exec 2>/dev/null
cp "$PWD/exec/image-info" "$HOME/.config/sxiv/exec/image-info"
cp "$PWD/exec/key-handler" "$HOME/.config/sxiv/exec/key-handler"
chmod +x "$HOME/.config/sxiv/exec/key-handler"
chmod +x "$HOME/.config/sxiv/exec/image-info"
