#!/bin/sh

check=$(which dunst)

[ -z "$DISPLAY" ] && [ -z $check ] && return;
mkdir -p $HOME/.config/dunst || echo 'Directory already exists'

ln -sf "$PWD/dunstrc" "$HOME/.config/dunst/dunstrc"
cp "$PWD/normal.png" "$HOME/.config/dunst/normal.png"
cp "$PWD/critical.png" "$HOME/.config/dunst/critical.png"
