#!/bin/sh
red="\[\e[31m\]"
green="\[\e[32m\]"
reset="\[\e[0m\]"

cmd=$(type "$1")

if [ -z "$cmd" ]; then
    printf "%b\n" "${red}WARNING:${reset} Looks like the package is not installed"
else
    printf "%b\n" "${green}CONFIRMATION:${reset} The package is installed."
fi
