#!/bin/sh

set -e
set -u

RED="\[\e[31m\]"
RESET="\[\e[0m\]"

test -n dmenu 2>/dev/stderr || echo '[!] Dmenu is not installed.'
# TODO: Implement dmenu and rofi choice
#type -p rofi || echo '[!] Rofi is not installed.'

choice=$(printf "shutdown\nreboot\nsleep\nsuspend" | dmenu -i -l 20 -p 'Run: ')
case $choice in
  'shutdown')
    cmd=$(printf "yes\nno" | dmenu -i -l 4 -p "Are you sure?[yes/no]")
    if [ "$cmd" = "yes" ]; then
      systemctl poweroff
    else
      exit 1
    fi
    ;;
  'reboot')
    cmd=$(printf "yes\nno" | dmenu -i -l 4 -p "Are you sure?[yes/no]")
    if [ "$cmd" = "yes" ]; then
      systemctl reboot
    else
      exit 1
    fi
    ;;
  'sleep')
    #TODO: See this through
    ;;
  'suspend')
    cmd=$(printf "yes\nno" | dmenu -i -l 4 -p "Are you sure?[yes/no]")
    if [ "$cmd" = "yes" ]; then
      systemctl suspend
    else
      exit 1
    fi
    ;;
  *)
    printf "%b\n" "${RED}WARNING:${RESET} Not a command." && exit 1
    ;;
esac
