#!/bin/sh

set -e
set -u

test -n dmenu 2>/dev/stderr || echo '[!] Dmenu is not installed.'
# TODO: Implement dmenu and rofi choice
#type -p rofi || echo '[!] Rofi is not installed.'

choice=$(echo -e 'shutdown\nreboot\nsleep\nsuspend' | dmenu -i -l 20 -p 'Run: ')
case $choice in
  'shutdown')
    cmd=$(echo -e "yes\nno" | dmenu -i -l 4 -p "Are you sure?[y/n]")
    if [ "$cmd" = "yes" ]; then
      systemctl poweroff
    else
      exit 1
    fi
    ;;
  'reboot')
    cmd=$(echo -e "yes\nno" | dmenu -i -l 4 -p "Are you sure?[y/n]")
    if [ "$cmd" = "yes" ]; then
      systemctl reboot
    else
      exit 1
    fi
    ;;
  'sleep')
    #TODO: See this through
    ;;
  'suspend')
    cmd=$(echo -e "yes\nno" | dmenu -i -l 4 -p "Are you sure?[y/n]")
    if [ "$cmd" = "yes" ]; then
      systemctl suspend
    else
      exit 1
    fi
    ;;
  *)
    exit 1
    ;;
esac
