#!/bin/sh

# This script is basically to set wallpaper when starting the computer as it does not require gui to start or any input
#
# The script uses doas and sudo as the root permission provider

wall=$(find $HOME/pix/wall -type f | shuf -n 1)
xwallpaper --zoom "$wall"
wal -c
wal -i ${wall} > /dev/null
sed -i 'N;$!P;D' "$HOME"/.cache/wal/colors-wal-dwm.h
(cd "$HOME"/repos/github.com/kunal/dwm && doas make clean install>/dev/null) && notify-send 'DWM' 'Restart DWM...'
