#!/bin/sh

echo "Choosing random wallpaper..." ;\
    wall=$(find $HOME/pix/wall -type f | shuf -n 1)

echo "Setting random wallpaper..." ;\
    xwallpaper --zoom "$wall"

echo "Generating pywal colorschemes..."
wal -c && wal -i $wall >/dev/null
sed -i 'N;$!P;D' $HOME/.cache/wal/colors-wal-dwm.h

echo "Recompiling dmenu..." ; \
    (cd $HOME/.local/src/dmenu && sudo make clean install&>/dev/null) && \
    notify-send -u critical "Dmenu recompiled..."

echo "Recompiling dwm..." ; (cd $HOME/.local/src/dwm && sudo make clean install>/dev/null) \
    && notify-send -u critical "Restart dwm..."

echo "Restart dwm for the new look"
