#!/usr/bin/env bash

echo "Choosing random wallpaper..." ;\
    wall=$(find $HOME/pix/wall -type f | shuf -n 1)

echo "Setting random wallpaper..." ;\
    xwallpaper --zoom "$wall"

echo "Generating pywal colorschemes..."
wal -c && wal -i $wall >/dev/null
#sed -i 'N;$!P;D' $HOME/.cache/wal/colors-wal-dwm.h
