#!/bin/sh

# check dependencies
dep_ck() {
  for pr; do
    type -ap $pr >/dev/null 2>&1 || echo -e "command $pr not found, install: $pr" 1
  done
}
dep_ck "sxiv" "xwallpaper"

# choose a wallpaper from the desired directory
path=$($HOME/pix/wall)
wal_set() {
  cmd=$(ls -c $path || echo "wallpaper directory does not exist.")
  sxiv -fto $cmd
}
walset=$(wal_set)

# set chosen wallpaper
xwallpaper --zoom $walset && wal -i $walset && echo "wallpaper and colorscheme changed" && notify-send "wallpaper set and colorscheme set..."

# for dwm
dep_ck "dwm"
