#!/bin/sh

check=$(cd $HOME/.config/lynx)
mkdir -p $HOME/.config/lynx
if [ -r $check ]; then
    ln -sf "$PWD/lynx.cfg" "$HOME/.config/lynx/lynx.cfg" && echo "[*] The symlink was made successfully!" && notify-send "Hey, listen..." "[*] The symlink was made successfully."
fi
